### ISSUE TITLE
Something wrong, please fix it.

### ISSUE THREAD

**Issue by johnsontse29** [kimxogus/react-native-version-check#1]
change to this code:
      const indexStart = text.indexOf(startToken);
      if (indexStart === -1) {
        latestVersion = text.trim();
        return Promise.resolve(latestVersion);
      }
      text = text.substr(indexStart + startToken.length);
      const indexEnd = text.indexOf(endToken);
      if (indexEnd === -1) {
        return Promise.reject("Parse error.");
      }
      text = text.substr(0, indexEnd);

**Comment by kimxogus** [comment]
@johnsontse29 Well, I'm not sure if that's wrong, but it seems that this code may improve performance. I'll try them soon. Thank you.
