### ISSUE TITLE
Playstore not detect Update

### ISSUE THREAD

**Issue by jeypc** [kimxogus/react-native-version-check#106]
Discussion.
I have already implemented the react native version check.
When there is the latest update, I direct the user to PlayStore, but in PlayStore there is no update, but it is open. Unless I close the application and try again the Update appears. Has anyone ever experienced something similar?

**Comment by MaximRikel** [comment]
I have the same thing. Only for me, no matter how many times I close the program, the Store always says "Open" instead of "Update". Any ideas why that is?
