### ISSUE TITLE
Does this package support incremental rollout in android?

### ISSUE THREAD

**Issue by louuysison** [kimxogus/react-native-version-check#108]
Just wanted to ask if this will work with incremental rollout in android? If the latest version is 2.3 and the rollout has not reached the user, will the user just be shown an update modal without the possibility to upgrade?

**Comment by rf1804** [comment]
@louuysison it depends on stores (google or apple), projects fetches the version which is live on store and according to response update check is there.

**Comment by vovkind** [comment]
> @louuysison it depends on stores (google or apple), project fetches the version which is live on store and according to response update check is there.

Hi.
Can you please explain how it works for iOS for staged rollout? Will the plugin recognise that the version is NOT ACTUALLY LIVE yet for all users?

Thanks a lot.
