### ISSUE TITLE
getLatestVersion regex

### ISSUE THREAD

**Issue by matheus0392** [kimxogus/react-native-version-check#118]
I was getting just a point '.' in getLatestVersion  function to get version from playStore, and just after changing

this:  `text.match(/Current Version.+>([\d.]+)<\/span>/)`
to this: `text.match(/Current Version.+?>([\d.]+)<\/span>/)`

it becames to work.

it seens to get until the last `</span>` from the page, not the next.

**Comment by JaimePata** [comment]
I had the same issue. Tested your solution and it worked!. However I noticed that it was already implemented in the latest version. 
I just needed to upgrade from 3.3.0 to 3.4.1.

**Comment by rf1804** [comment]
Already there with latest version
