### ISSUE TITLE
getVersion response is cached on iOS

### ISSUE THREAD

**Issue by fernandopena** [kimxogus/react-native-version-check#119]
It's not necessarily an issue but it depends on the use case. I report it here in case someone else experience the same issue and wonder why it's happening.
I'm using this library to check if there is a new version available on the store at application launch. The problem I'm facing is that the response of the getVersion method of AppStoreProvider gets cached for a day.

https://itunes.apple.com/${countryCode}lookup?bundleId=${opt.packageName}}

Response header: Cache-Control: max-age=86358

If this caching represents an issue it can be solved by adding a timestamp or a random number to the call.

Ex: https://itunes.apple.com/${countryCode}lookup?bundleId=${opt.packageName}}&_=${Date.now()}

**Comment by BoKKeR** [comment]
We are facing the same issue, I will be opening a PR

**Comment by BoKKeR** [comment]
Looking at the source code it is already included since 2 months ago, but its not in the latest 3.4.1 release. Could you push this out? @kimxogus 

https://github.com/kimxogus/react-native-version-check/blob/07d3f1d901de908d393f640b087e9d5315eb70e0/packages/react-native-version-check/src/providers/appStore.js#L33

**Comment by akhlopyk** [comment]
@BoKKeR good to know about it.
Do you have an idea if there is a way to reset that cache? I have deployed the app yesterday and still an old version is coming from API.

**Comment by BoKKeR** [comment]
I had luck testing the feature when I launched the app on a new simulator.

**Comment by kimxogus** [comment]
Just published https://github.com/kimxogus/react-native-version-check/releases/tag/v3.4.2
Sorry for late response
