### ISSUE TITLE
expo module version not including most of the provided functions.. 

### ISSUE THREAD

**Issue by Hiti3** [kimxogus/react-native-version-check#121]
So does this work on expo, full features as listed in the readme? 

Because after installing `npm install --save react-native-version-check-expo` the given feature just does not work. Is this function even supported in the expo version?

`import VersionCheck from 'react-native-version-check-expo'`

`       
 VersionCheck.getCurrentVersion().then(version => console.log(version)); // OK
`
`
        VersionCheck.getLatestVersion({
            provider: 'playStore'
        })
            .then(latestVersion => {
                console.log(latestVersion);    // Unresolved function or module
            });
`

**Comment by Hiti3** [comment]
SOLVED: One needs to install both packages,` react-native-version-check` as well as `react-native-version-check-expo` in order for expo package to provide the features.

**Comment by calebswank11** [comment]
@Hiti3 I also ran into this issue but the installation of both does not solve it. I can get a subset of the methods but items like needUpdate and getLatestVersion always return undefined. Any thoughts or tips on how you got it to work?

**Comment by Hiti3** [comment]
@calebswank11 Bellow code made it work for me under the above assumption both need to be instaled but only used expo one as package import. 

`    const checkVersion = () => {
        let current = VersionCheck.getCurrentVersion();
        let updated = current;
        VersionCheck.getLatestVersion({
            provider: 'playStore'
        })
            .then(latestVersion => {
                updated = latestVersion;
            });
        console.log("Current version:", current);
        console.log("New version available:", updated);
        if (current !== updated) {
            setForceUpdate(true);
        }
    };`
