### ISSUE TITLE
 Update Issue

### ISSUE THREAD

**Issue by FilipeT10** [kimxogus/react-native-version-check#127]
I have a problem that when calling the method
needUpdate without passing any parameters it returns "isNeeded: true" but when entering google play through the link provided there only appears the option Open as if there was no update. . Could someone help me please.

**Comment by somchithCom2** [comment]
Same here, after navigating to play store, It gives an "open" button instead of update one

**Comment by Hadajung** [comment]
same here

**Comment by decentname** [comment]
Same issue

**Comment by Fernando922** [comment]
same problem!!!

**Comment by rf1804** [comment]
Issue is with the play store as it is taking some extra time to show updates or may be it's cache issue.
After refreshing play store or waiting for few minutes it shows up the update.
