### ISSUE TITLE
VersionCheck.needUpdate()

### ISSUE THREAD

**Issue by AlessioCamm** [kimxogus/react-native-version-check#130]
Hi. Can someone know why `testLatestVersion` return `undefined` ?
```
try {
      let testLatestVersion = await VersionCheck.needUpdate();
      console.log('testLatestVersion', testLatestVersion)
}
catch(error){
    console.log('ERROR')
 }
```
Without `async` & `await`, it return a simple promise, so I never get the answer...

**Comment by KicassOS** [comment]
It most likely logs undefined because the log happens when the Promise hasn't finished executing yet.
You should wrap the whole thing in an async function or use .then().
`VersionCheck.needUpdate().then(v => console.log(v)).catch(err => console.log("error"))`

**Comment by rf1804** [comment]
It is a query not an issue.
