### ISSUE TITLE
Question how does force update work?

### ISSUE THREAD

**Issue by AlmogRnD** [kimxogus/react-native-version-check#14]
I'm not sure I fully understand this part "provider: () => fetch('http://your.own/api')"

**Comment by kimxogus** [comment]
Latest Version data is stored [in this library](https://github.com/kimxogus/react-native-version-check/blob/master/packages/react-native-version-check/src/getLatestVersion.js#L6), and will be stored at the first provider call.
If `forceUpdate` option is false and `latestVersion` data is stored. Provider call will not be executed and returns the stored `latestVersion` immediately.

**Comment by kimxogus** [comment]
Ah, now I found an bug related to storing latestVersion. I'll fix that.

**Comment by jenskuhrjorgensen** [comment]
@kimxogus Thanks for the explanation. I think you should put this in the README 😄  Thanks for the library!
