### ISSUE TITLE
In Android, VersionCheck.getLatestVersion() is not working

### ISSUE THREAD

**Issue by heekyu-pu** [kimxogus/react-native-version-check#151]
version: 3.4.2

RN versions : 0.63.2, 0.64.1, 0.66.3

VersionCheck.getLatestVersion() returns Promise<undefined>

same code works in 1 month ago, but not working now

**Comment by dkfox** [comment]
same here

**Comment by StevenChen0824** [comment]
same here, maybe because google change to format of there html, so can't get the version code?

**Comment by nustony** [comment]
Is there any solution to this problem?

**Comment by 15110011** [comment]
any update?

**Comment by yamila-fraiman** [comment]
Same issue!

**Comment by aestebancl1989** [comment]
Same for me

**Comment by gloria8924** [comment]
same here

**Comment by yujin-noh** [comment]
I solved this problem
[PR 158](https://github.com/kimxogus/react-native-version-check/pull/158)

**Comment by FahrizalAziFerdiansyah** [comment]
im still same problem

**Comment by rf1804** [comment]
Latest version has been released v3.4.3

https://www.npmjs.com/package/react-native-version-check/v/3.4.3
