### ISSUE TITLE
[Alternative] https://github.com/flexible-agency/react-native-check-version

### ISSUE THREAD

**Issue by bang9** [kimxogus/react-native-version-check#159]
https://github.com/flexible-agency/react-native-check-version

**Comment by ZZANZU** [comment]
이런 라이브러리도 있었군요...! 감사합니다. 혹시 프로덕션에 적용해보셨나요? 이슈는 없으신가요?

**Comment by ZZANZU** [comment]
@bang9

앗, 사운드짐이셨군요?!?! 반갑습니다! 진짜 한 번 뵀을 수도 있었겠네요ㅎㅎ

말씀해주신대로 저희도 서버 쪽에 API 하나 만들어서 내부적으로 최신 버전 여부를 리턴해줄까 검토중입니다!

감사합니다ㅎㅎ
