### ISSUE TITLE
RNVersionCheck.country

### ISSUE THREAD

**Issue by krrevilla** [kimxogus/react-native-version-check#16]
After I imported the plugin, I've received an error "Undefined is not an object (evaluating 'RNVersionCheck.country')

**Comment by kimxogus** [comment]
Can you try [`RNVersionCheck.getCountryAsync()`](https://github.com/kimxogus/react-native-version-check#methods)? It will return a promise with `country` string value.

**Comment by krrevilla** [comment]
I haven't use a function, i just put `import VersionCheck from 'react-native-version-check'`

**Comment by krrevilla** [comment]
Would it work even if my app is still on closed beta in the play store ?

**Comment by kimxogus** [comment]
If your app is visible by normal http request, it will work.

**Comment by krrevilla** [comment]
Ah, my bad. Thanks @kimxogus will close it now.

**Comment by Ble3k** [comment]
Hi, reopen it, please. I'm facing the same issue on iOS, my app is in app store production now. I have updated react-native-version-check from 2.0.1 to 2.3.0, then started to face this issue. I just imported VersionCheck from 'react-native-version-check', nothing else. Debugger shows that error is in the package.

http://joxi.net/V2V3lWkS0ZOpXA

**Comment by kimxogus** [comment]
As you see in the [code](https://github.com/kimxogus/react-native-version-check/blob/master/packages/react-native-version-check/src/RNVersionInfo.js#L7).
It seems that native module is not loaded properly. Can you make sure that react-native-version-check is linked?

**Comment by kunall17** [comment]
Facing the same error in 2.0.1 and 2.3.0
![simulator screen shot - iphone 6 - 2018-01-24 at 11 17 12](https://user-images.githubusercontent.com/12700799/35316544-4272d18c-00f8-11e8-8504-197c2068de24.png)

**Comment by Ble3k** [comment]
Hi, I tried to unlink->uninstall->clear cache->install->link package, and still get the same error. How else can I make sure react-native-version-check is linked?

**Comment by Ble3k** [comment]
I reinstalled react-native-version-check now but version 2.2.0 and not facing this error. But I need version 2.3.0 because of this https://github.com/kimxogus/react-native-version-check/pull/20

**Comment by kunall17** [comment]
After doing react native link PackageName it worked in mine!

**Comment by kimxogus** [comment]
#20 has only changes in store provider and it should have no effect on native modules.
@Ble3k  Can you try again with 2.2.1?

**Comment by Ble3k** [comment]
Ok, I will try later and answer, thx

**Comment by krrevilla** [comment]
Hi @kimxogus, I have a question. 

Is this working for an application, that's still on Open Beta ? I have an app in open beta, and by calling `VersionCheck.getLatestVersion()`. I only get "Parse error.'
