### ISSUE TITLE
needUpdate consistently returning null for Android

### ISSUE THREAD

**Issue by faizanbutt** [kimxogus/react-native-version-check#164]
I am using VersionCheck.needUpdate({ country: 'us' }) but it is consistently returning me null for Android. Don't know if anyone else is also facing this issue.
Earlier it was working perfectly.
I have an app on google play and most of the users are facing problems due to this issue.

Please check ASAP.
Thanks!

**Comment by Wissam-Yelhow** [comment]
Yes this is recent due to PlayStore UI changes, check the last two issue reports:

https://github.com/kimxogus/react-native-version-check/issues/161
https://github.com/kimxogus/react-native-version-check/issues/162

**Comment by Rafael-Pessoni** [comment]
Anyone here knows the solutions for this trouble? I'm getting this error on a published app, and I need to resolve quickly... Please :/

**Comment by M4Tdev** [comment]
This package (https://github.com/flexible-agency/react-native-check-version) has been updated to work with the new Google Play Store design, it is still not the best solution but it does work at least for now, till we find a better way.

**Comment by Joan0018** [comment]
@Rafael-Pessoni Do you found any workable solution? I getting error on a pubilshed app also

**Comment by rf1804** [comment]
Latest version has been released v3.4.3

https://www.npmjs.com/package/react-native-version-check/v/3.4.3
