### ISSUE TITLE
Play Store layout change

### ISSUE THREAD

**Issue by asad-cygnis** [kimxogus/react-native-version-check#171]
Hi, Library is broken for android. Since the new layout is introduced by the google play store. I have seen you guys have done a marvelous job by handling the new layout, particularly in commit `af570753050eef0070803ec82df873abe3c1ad47` on June 21, 22.

Can you please tell me when will you release a new version of the library with this fix?

@AdeilsonESilva

**Comment by AdeilsonESilva** [comment]
I hope that as soon as possible, we need to see with the maintainers. @kimxogus

**Comment by rf1804** [comment]
Latest version has been released v3.4.3

https://www.npmjs.com/package/react-native-version-check/v/3.4.3
