### ISSUE TITLE
Typescript error VersionCheck.getLatestVersion

### ISSUE THREAD

**Issue by buscanopaul** [kimxogus/react-native-version-check#201]
Hi,

I have this error with typescript with provider 

VersionCheck.getLatestVersion({
  provider: () => fetch('http://your.own/api')
    .then(r => r.json())
    .then(({version}) => version),   // You can get latest version from your own api.
}).then(latestVersion =>{
  console.log(latestVersion);
});

It says
Type '() => Promise<any>' is not assignable to type 'string | (() => string) | undefined'.
  Type '() => Promise<any>' is not assignable to type '() => string'.
    Type 'Promise<any>' is not assignable to type 'string'.

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=q3-Mrwd1Vm0
