### ISSUE TITLE
Versioncheck needupdate function returning error in ios

### ISSUE THREAD

**Issue by sukumardv3101** [kimxogus/react-native-version-check#21]
For ios added appid and appname.
on checking need update function throwing promise rejection error.

here is my code snippet
if(Platform.OS === 'ios'){
      VersionCheck.setAppID(13******98);                    // Your App ID for App Store URL
     VersionCheck.setAppName('app name'); 
  }

   VersionCheck.needUpdate().then(res => {
           console.log(res);
   })
   .catch( err => {
          console.log(err); 
   })

**Comment by kimxogus** [comment]
can you provide more details of the error? like error messages...

**Comment by sukumardv3101** [comment]
here is the
[doc.txt](https://github.com/kimxogus/react-native-version-check/files/1649626/doc.txt)
 html file am getting in error response.

**Comment by kimxogus** [comment]
I think #20 will fix this issue.

**Comment by sukumardv3101** [comment]
Am getting correct store url but needupdate() and getlatestversion() functions on execution returning error.

**Comment by kimxogus** [comment]
Yes store url is ok, but their rendered html on the store page has changed. That's why it's throwing error.
#20 is now on review, and its author said that requested changes will be applied by Monday or Tuesday.
I'll merge and publish that by then.

**Comment by sukumardv3101** [comment]
thanks @kimxogus ,

**Comment by AlmogRnD** [comment]
+1 getting the same error

**Comment by kimxogus** [comment]
#20 is merged. I'll publish new version with updated readme.

**Comment by sukumardv3101** [comment]
is that new version published ?

**Comment by kimxogus** [comment]
just published 2.3.0
