### ISSUE TITLE
iOS Version check not working when outside the US and app not added to US Store

### ISSUE THREAD

**Issue by allyburns** [kimxogus/react-native-version-check#23]
We have an app that is only available in the GB store (NOT in the US store).

We see that the library uses the following url to get our version info:

https://itunes.apple.com/lookup?id=1327861046

This returns no results:
`{
 "resultCount":0,
 "results": []
}`

However, if the country code is added to the URL we get the expected results.
https://itunes.apple.com/lookup?id=1327861046**&country=GB**

I believe that the solution would be to always add the country code to the lookup URL, but not sure if this would have any side effects?

Alternatively make this an option that if specified and not blank will be used as part of the lookup url (the same way that the id and store name are set as options for iOS).

**Comment by allyburns** [comment]
Just spotted that someone has done a pull request to fix the issue, should have looked there first!

https://github.com/kimxogus/react-native-version-check/pull/22

**Comment by kimxogus** [comment]
Just merged #22 and published 2.3.1.
