### ISSUE TITLE
Xcode Error: 2 duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by mcampsall** [kimxogus/react-native-version-check#25]
I have installed this all manually following your readme, and when I link the library:

<img width="324" alt="screen shot 2018-01-24 at 2 30 02 pm" src="https://user-images.githubusercontent.com/15930818/35360600-1d3f2378-0113-11e8-9b05-44636eb7ed95.png">

I get an build failure error:

```duplicate symbol _OBJC_CLASS_$_RNVersionCheck in:
    /Users/.../Library/Developer/Xcode/DerivedData/.../Build/Products/Debug-iphonesimulator/react-native-version-check/libreact-native-version-check.a(RNVersionCheck.o)
    /Users/.../Library/Developer/Xcode/DerivedData/.../Build/Products/Debug-iphonesimulator/libRNVersionCheck.a(RNVersionCheck.o)
duplicate symbol _OBJC_METACLASS_$_RNVersionCheck in:
    /Users/.../Library/Developer/Xcode/DerivedData/.../Build/Products/Debug-iphonesimulator/react-native-version-check/libreact-native-version-check.a(RNVersionCheck.o)
    /Users/.../Library/Developer/Xcode/DerivedData/.../Build/Products/Debug-iphonesimulator/libRNVersionCheck.a(RNVersionCheck.o)
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mcampsall** [comment]
hmmm, in the simulator I seem to be getting results back from:

`VersionCheck.getCountryAsync()
  .then(country => console.log(country));          // US
console.log(VersionCheck.getPackageName());        // com.my-react-native-app
console.log(VersionCheck.getCurrentBuildNumber()); // 1715
console.log(VersionCheck.getCurrentVersion());     // 3.0`

is it possible this is working without needing to manual link the library?

**Comment by kimxogus** [comment]
if you already linked with `react-native link`, you don't need manual link
