### ISSUE TITLE
getStoreUrl will not work in expo. Please use "getCountryAsync()"

### ISSUE THREAD

**Issue by code-by** [kimxogus/react-native-version-check#27]
I using `getStoreUrl` for open Google Play / Apple Store if users version is outdated, but get this warn:

`getStoreUrl will not work in expo. Please use "getCountryAsync()" instead. This will be deprecated from v3`

but I don't understand - `getStoreUrl` is for open application in Google Play or in App Store, while `getCountry` / `getCountryAsync` is for display country name. Or I miss something?

p.s. I don't use Expo

**Comment by kimxogus** [comment]
It seems to be a typo. Thanks for reporting
