### ISSUE TITLE
`checkIfUpdateNeeded` doesn't work properly when there are zeros in the version

### ISSUE THREAD

**Issue by leonardocarvalho** [kimxogus/react-native-version-check#28]
The first check in `checkIfUpdateNeeded` loop is

```js
if (!latestVersionToken && !currentVersionToken) {
    return Promise.resolve(notNeeded);
}
```

If versions are 0.1 and 0.2, or 1.0.1 and 1.0.2 the function will answer wrongly that update is not needed.

**Comment by leonardocarvalho** [comment]
If you think this is an issue I can try sending a PR to fix it.

**Comment by kimxogus** [comment]
I checked this case with test code and it returns `true` for 0.1 and 0.2 or 1.0.1 and 1.0.2
I'm going to replace version comparison code with `semver`.
