### ISSUE TITLE
Different between getStoreUrlAsync and getStoreUrl

### ISSUE THREAD

**Issue by ridhwandaud** [kimxogus/react-native-version-check#29]
I got this error  **"Unhandled Promise Rejection"** in sentry tracker using your package 2.0.0-alpha.3. Checking the new version 2.3.1 . I notice that there are new updated getStoreUrlAsync. Will this help me to handle the Unhandled Promise Rejection ? I did not use async and await for getting the getStoreUrl in my code.

**Comment by kimxogus** [comment]
Well, can you provide details of the promise rejection?

**Comment by rf1804** [comment]
Closing as issue is not relevant.
