### ISSUE TITLE
TypeError: Cannot read property of undefined

### ISSUE THREAD

**Issue by lefoy** [kimxogus/react-native-version-check#32]
I'm trying to use this library on iOS but I always get the `Cannot read property [...] of undefined` . I tried installing using NPM/link and Pods but no success. I'm simply trying to get the current package name using this library. My code is `console.log(VersionCheck.getPackageName());`.

I also tried using the needUpdate method, but I get a similar error message `TypeError: Cannot read property 'currentVersion' of undefined`.

Any idea of how I could fix this issue? Let me know if you need more info. Thanks!

Edit: I'm using `"react-native-version-check": "^3.0.0-rc.2"`

**Comment by Northshoot** [comment]
did you find a solution?

**Comment by mjtpena** [comment]
@lefoy did you find a solution?

**Comment by mjtpena** [comment]
I think there's a problem with automatic linking the iOS library ung `react-native link react-native-version-check`. I did manual linking, and it now works.

**Comment by lefoy** [comment]
@mjtpena I ended up using https://github.com/rebeccahughes/react-native-device-info

**Comment by jenskuhrjorgensen** [comment]
I also ended up linking it manually for iOS because of the same error as the OP followed by some `Duplicate module name: react-native` error.

**Comment by rf1804** [comment]
Manual or `react-native link` has been depreceated, please follow new rules as per official react-native docs

- `yarn add react-native-version-check` or `npm install react-native-version-check`

- Only for ios: `pod install` or `pod update as per requirement`
