### ISSUE TITLE
iOS: undefined is not an object (evaluating 'option.appID') on VersionCheck.needUpdate()

### ISSUE THREAD

**Issue by aauffray** [kimxogus/react-native-version-check#35]
Hi ! I'm implementing this module on my App and when I run on iOS I get this error in my logs:

undefined is not an object (evaluating 'option.appID')
	getAppStoreUrl$@http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:152698:45
	tryCatch@http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:35294:44
	invoke@http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:35482:30
	tryCatch@http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:35294:44
	invoke@http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:35352:28
	http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:35382:17
	tryCallTwo@http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:35009:7

The app version is visible on the AppStore, if that would have been a problem in any case
How can I fix this ?

**Comment by tschoffelen** [comment]
Can you show the code that you are using to call the library?
