### ISSUE TITLE
Fatal Exception: NSInvalidArgumentException

### ISSUE THREAD

**Issue by AhmedAliIbrahim** [kimxogus/react-native-version-check#38]
Hello,
I've the package installed on one of my application, few weeks ago i've started see crashes on my app, and since i've Fabric installed i found that the issue in the below line !! any help how to fix it ?! or why even this happens ?!
[RNVersionCheck constantsToExport] (RNVersionCheck.m:42)

**Comment by kimxogus** [comment]
Honestly, I have no experience in ios development. I think other ios expert is needed.

Sorry for late response. github didn't send me noti for this issue....
