### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by gjvpaet** [kimxogus/react-native-version-check#40]
Apparently, google playstore changed their markup for the current version so the plugin throws a parse error every time although it works perfectly before. I think the parsing needed an update to adapt to the changed Google made in the current version markup.

**Comment by gerdana2405** [comment]
Any updates? I have the same issue.

**Comment by gjvpaet** [comment]
@leoleung0102 yeah that's exactly what my issue I think it's the same for everyone.

**Comment by Carl0395** [comment]
I have the same issue.

**Comment by denisdimitrov** [comment]
+1

**Comment by svetoslav0625** [comment]
+1

**Comment by damsorian** [comment]
+1 same issue

**Comment by krrevilla** [comment]
+1 same issue on my current project, any update on this ?

**Comment by denisdimitrov** [comment]
He just published 3.0.0-rc.5 with the fix. Feel free to dl it.

**Comment by leoleung0102** [comment]
@denisdimitrov Thank for your help

**Comment by gjvpaet** [comment]
Thanks @denisdimitrov
