### ISSUE TITLE
TypeError: Cannot read property 'ignoreErrors' of undefined

### ISSUE THREAD

**Issue by liplylie** [kimxogus/react-native-version-check#42]
This happens when I use `VersionCheck.getStoreUrl()`

Version 3.0.0-rc.5

**Comment by MikhailSemichev** [comment]
Can anyone propose some workaround?

**Comment by krszwsk** [comment]
For a quick workaround you can hard-code store urls in your app. I don't see anything that could go wrong with this solution if you distribute one app without variations.
