### ISSUE TITLE
Version check not working in production 

### ISSUE THREAD

**Issue by liplylie** [kimxogus/react-native-version-check#45]
Version: 3.0.0-rc.4

The version check works fine locally in development.

However, I just updated my app in the App Store, and haven’t received an in app alert for the update.

Tried again after 3 hours, and haven’t received an alert.

Also, both my currently installed build and updated build are using rn version check.

What should I do?

**Comment by kimxogus** [comment]
Is latest version published?
This library parse latest version info from webpage of your app in App Store.
If that's not updated yet, it can't determine if update is needed.

If your app is already published, check if it satisfies [semver](https://github.com/kimxogus/react-native-version-check/blob/master/packages/react-native-version-check/src/needUpdate.js#L97)

**Comment by liplylie** [comment]
I just received the in app alert.

I suppose the app just needed a bit of time to process while being on the App Store.
