### ISSUE TITLE
Data is not being fetched when VersionCheck.needUpdate is called inside react's lifecycle method

### ISSUE THREAD

**Issue by jorgefernandes** [kimxogus/react-native-version-check#51]
I'm trying to use VersionCheck.needUpdate method inside my component scope so i can call prop's methods on needUpdate callback: 

```
componentDidMount() {
      VersionCheck.needUpdate({
        depth: 2,
      }).then((res) => {
        console.log('res', res);
        if (res.isNeeded === true) {
           // call this.props.someMethod();
        }
        return null;
      });
}
```

but .then() is never reached. 
Digging into package's code i saw that when i call VersionCheck.needUpdate, fetch() method is not returning any data when it request https://play.google.com/store/apps/details?id=, for instance.

Does anyone have any solution to this?

**Comment by rf1804** [comment]
Resolved with the linked Pull Request
