### ISSUE TITLE
The SDK Build Tools revision (23.0.1) is too low for project ':react-native-version-check'. Minimum required is 25.0.0

### ISSUE THREAD

**Issue by SukumarSmart** [kimxogus/react-native-version-check#52]

**Comment by kimxogus** [comment]
@tschoffelen can you investigate this?

**Comment by tschoffelen** [comment]
Hi @SukumarSmart, could you give a little more context around this issue? For example, what React Native version are you using, and what version of the Android Build Tools are you using in your project (can be found in file `android/app/build.gradle`)?

Our default version is 26.0.3, so either you're overriding that somewhere in your project, or your project is using an old version of Gradle.

https://github.com/kimxogus/react-native-version-check/blob/master/packages/react-native-version-check/android/build.gradle#L5

**Comment by mgenov** [comment]
I've encountering similar thing when importing the example project:

![image](https://user-images.githubusercontent.com/209223/52523076-15903680-2c96-11e9-8735-d46b8ce5b854.png)

**Comment by rf1804** [comment]
Resolved with the latest release
