### ISSUE TITLE
control react-native version from app project 

### ISSUE THREAD

**Issue by mgenov** [kimxogus/react-native-version-check#58]
It would be good if react-native version is controlled from the parent project instead of defining concrete version internally. 

```gradle
def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

dependencies {
  implementation "com.facebook.react:react-native:${safeExtGet('reactNativeVersion', '+')}"
}
```

e.g this snippet will ensure that project could specify rn version on it's own.

**Comment by kimxogus** [comment]
Thank you for good suggestion :)

Can you make a PR?

**Comment by mgenov** [comment]
I've tried yesterday but I wasn't able to import successfully the project in Android Studio. Later today will give it a second try.

**Comment by rf1804** [comment]
Resolved with the latest version
