### ISSUE TITLE
appName or appID is undefined

### ISSUE THREAD

**Issue by Tako** [kimxogus/react-native-version-check#6]
these methods return well:

    console.log(VersionCheck.getCountry());            // KR
    console.log(VersionCheck.getPackageName());        // com.reactnative.app
    console.log(VersionCheck.getCurrentBuildNumber()); // 10
    console.log(VersionCheck.getCurrentVersion());     // 0.1.1

but the others like VersionCheck.getLatestVersion()

return an error : appName or appID is undefined.

VersionCheck.setAppID(CONFIG.ITUNE_INFOS.id);
VersionCheck.setAppName(CONFIG.ITUNE_INFOS.name);

are setted correctly i think :/

**Comment by kimxogus** [comment]
Sorry, I must have made some silly mistakes in renaming.
Please update to v1.2.2.

**Comment by Tako** [comment]
Thx for the update :)
