### ISSUE TITLE
 TypeError: undefined is not an object (evaluating 'RNVersionCheck.currentVersion')

### ISSUE THREAD

**Issue by saraswathirbt** [kimxogus/react-native-version-check#60]
I have used the method  VersionCheck.needUpdate() . In xcode it throws an error undefined is not an object (evaluating 'RNVersionCheck.currentVersion') . Can anyone help me to solve this error. Thanks in advance

**Comment by tschoffelen** [comment]
Hi,

It seems like the native dependency might have not been installed correctly.

Could you try running `react-native link react-native-version-check` and re-compile your app?

**Comment by saraswathirbt** [comment]
Hi @tschoffelen thanks  for your reply, I tried doing react-native link react-native-version-check but the same error exist in xcode and I also tried by adding the package manually and it works now

 [Error: At least one of appID and appName is empty.]
  line: 176908,
  column: 28,
  sourceURL: 'http://192.168.244.104:8081/index.bundle?platform=ios&dev=true&minify=false' }
now xcode throws the above error

**Comment by longunibbo** [comment]
I'm running into same issue with you. but I cannot find out libRNVersionCheck.a to add to my project. Can you tell me how to do it correctly?
I already did this: react-native link react-native-version-check

**Comment by longunibbo** [comment]
This is my react-native-version-check folder after yarn add

![image](https://user-images.githubusercontent.com/38639215/56097354-1c009000-5f1d-11e9-9fc6-96d10203d45f.png)

**Comment by tschoffelen** [comment]
Hi @longunibbo. That is correct, this package doesn't have any external dependencies, so `node_modules` should indeed be empty.

The `libRNVersionCheck.a` is a file you should be able to find when opening your (main) project in Xcode, then expanding Libraries > RNVersionCheck > Products in the file tree in the left panel.

**Comment by alisonysy** [comment]
Same here, when I run `react-native link react-native-version-check`, it said it was linked successfully. But in fact, it wasn't. 
Then I mannually linked the package in XCode according to the ios mannual installation guide. But when I ran it, errors of duplicate libraries occurred. 
After I removed the reference of `RNVersionCheck.xcodeproj` target in the `Libraries` folder in XCode, the app can run! And no more `TypeError: undefined is not an object (evaluating 'RNVersionCheck.currentVersion')`

**Comment by rf1804** [comment]
Manual or `react-native link` has been depreceated, please follow new rules as per official react-native docs

- `yarn add react-native-version-check` or `npm install react-native-version-check`

- Only for ios: `pod install` or `pod update` as per requirement
