### ISSUE TITLE
When the MARKETVERSION_STARTTOKEN is not found, getLatestVersionFromUrl returns the whole HTML page.

### ISSUE THREAD

**Issue by VincentFTS** [kimxogus/react-native-version-check#7]
In the getLatestVersionFromUrl function, if the MARKETVERSION_STARTTOKEN is not found, the functions returns the whole HTML page:
`    const indexStart = text.indexOf(MARKETVERSION_STARTTOKEN);
    if (indexStart === -1) {
      latestVersion = text.trim();
      return Promise.resolve(latestVersion);
    }
`
In this case, we should reject the promise : 
`      return Promise.reject('Parse error.');
`
like when the MARKETVERSION_ENDTOKEN is not found.

This issue happens when the network is off.

**Comment by kimxogus** [comment]
Thank you for the issue :)

I'll fix it soon

**Comment by VincentFTS** [comment]
Can you give an ETA ?
I would need this for a release next Tuesday…

**Comment by kimxogus** [comment]
Oh I see. I'm trying to fix this in this weekend.
I made some test cases to retrieve latest version and I tested without internet connection. Promise rejection works. I think it should reject by fetch before that code without internet connection. Can you give me more information about the error?

**Comment by VincentFTS** [comment]
You’re right, fetch should reject the Promise. I'm investigating on my own on this issue.
Whatever, I think you should apply the correction I gave, in case of store server unreachable for exemple…

**Comment by kimxogus** [comment]
That's intended for custom api. If you use custom latest version api. It may return only version info which doesn't contain `MARKETVERSION_STARTTOKEN`. Then it will return entire response from api.

**Comment by VincentFTS** [comment]
If, one day, the apple server returns an error html page or an "App Store server update in progress" html page, the getLatestVersion call will return the whole html page instead of what should be a version string ! Promise user will have an unpredictable behavior then.

**Comment by kimxogus** [comment]
I agree. I'll come up with some other way to prevent that. For now, it's not going to be changed. It will influence apps using custom latest version api.

**Comment by kimxogus** [comment]
Thank you for your opinion

**Comment by VincentFTS** [comment]
I didn’t pay attention to the custom API, sorry.
You may have a specific behavior for the default stores URLs then.

Concerning my use case, I achieved to reproduce it, but I misunderstood what happened:
I first get the last version number and then shut down network. I expected to see the Promise rejected, but it didn’t. It seems to be due to caching, since I get a version number whereas the network is down.

I don’t really know if it is a desirable behavior…

**Comment by kimxogus** [comment]
I've just released `2.0.0-alpha.1` with provider option support.
