### ISSUE TITLE
forceUpdate

### ISSUE THREAD

**Issue by porknoodles** [kimxogus/react-native-version-check#8]
Hi, I'm doing an apps for android and ios.
it seems that `forceUpdate: true` only work iOS, I might be using it the wrong way or understand it the wrong way.
forceUpdate: true function is to prevent user from not updating to the latest apps right?
say if I display alert, a modal, user shouldn't be able to click the grey area outside the modal, right?
Please, help....

**Comment by kimxogus** [comment]
No.
`getLatestVersion` stores the latest version and returns the stored latest version after first request.
`forceUpdate: true` option makes `getLatestVersion` function not to use stored one and make a request again.
