### ISSUE TITLE
'react-native' conflict

### ISSUE THREAD

**Issue by CarlaTeo** [kimxogus/react-native-version-check#84]
When updating dependencies in https://github.com/kimxogus/react-native-version-check/commit/7f506bbd5758035ce797dc57af802a88244e6a9f I believe you forgot to increase RN version in peerDependencies too.

I tried using the newest version but I had a conflict of RN versions.

**Comment by kimxogus** [comment]
`lerna publish` didn't respect `.npmignore` and that caused `react-native-version-check/src/node_modules` to be published.
It was fixed in #86 and published as [v3.2.1](https://github.com/kimxogus/react-native-version-check/releases/tag/v3.2.1)
