### ISSUE TITLE
VersionCheck.needUpdate() returns undefined in IOS

### ISSUE THREAD

**Issue by yasir-netlinks** [kimxogus/react-native-version-check#91]
This is the code I'm using
```
VersionCheck.needUpdate().then(res => {
      console.log("res version check >>>>>> ", res); // undefined on iOS
      if (res.isNeeded) {
        this.setState({
          showNewVersionModal: true
        });
      }
    });
```
it works fine on `Android` but on `iOS` it returns `undefined` 

Version:
"react-native-version-check": "^3.3.0",
"react-native": "^0.57.8",

**Comment by tschoffelen** [comment]
Hi @yasir-netlinks,

Is (an earlier version of) your app already live in the app store? Otherwise we can't find out what the App ID of the app is, which might be why `undefined` is returned.

**Comment by yasir-netlinks** [comment]
@tschoffelen  yes, there is a version live in AppStore. maybe there is a way I could that manually?

**Comment by LucianHij** [comment]
I am experiencing the same issue.

**Comment by tvhimanshu** [comment]
Getting same issue Anyluck @yasir-netlinks

**Comment by yasir-netlinks** [comment]
@jeveloper @tvhimanshu I didn't have the time (was running out of time) to solve this particular issue, so I went ahead using this package for ios only `react-native-appstore-version-checker` one thing I didn't like here is that I have my current release version `hard-coded` in a config file to check against it
```
if (Platform.OS === "ios") {
      getAppstoreAppVersion("app id") //put any apps id here
        .then(appVersion => {
          if (appVersion > config.IOS_APP_VERSION_IN_STORE) {
            this.setState({
              showNewVersionModal: true
            });
          }
        })
        .catch(err => {
          return;
          // console.log("error occurred", err);
        });
    }
```

**Comment by joony0123** [comment]
If anyone is still struggling, I highly suggest to try this:

https://github.com/kimxogus/react-native-version-check/issues/92#issuecomment-599263319

**Comment by zigoval** [comment]
i had the same issue before :
- I think it's not working on the emulator
- try to specify the provider : 
```
      VersionCheck.needUpdate({
        currentVersion: version,
        provider: 'appStore',
      })

```

**Comment by rf1804** [comment]
Manual or `react-native link` has been depreciated, please follow new rules as per official react-native docs

- `yarn add react-native-version-check` or `npm install react-native-version-check`

- Only for ios: `pod install` or `pod update` as per requirement

**Comment by bahtiyarerden** [comment]
I installed this package with autolinking but this problem still exist.

**Comment by AnasAlamin** [comment]
> If anyone is still struggling, I highly suggest to try this:
> 
> [#92 (comment)](https://github.com/kimxogus/react-native-version-check/issues/92#issuecomment-599263319)

i'm using expo managed flow, how can i solve this?

**Comment by crosswin-ecgroup** [comment]
Try to run this command `npx pod-install` and rebuild the project.

**Comment by iwangsyah** [comment]
You can check your app url in browser, maybe they has a specific country code. you can add params for country code like this `VersionCheck .needUpdate({country: <your-country-code>})`

This works for me

**Comment by usmanrwp** [comment]
1. react-native link
2. Close metro server
3. uninstall app
4. clean project
5. reinstall app
works for me
